

---rollback:
DROP ROLE IF EXISTS DEMO1_ROLE;

---version: 0
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEMO1_ROLE;

---version: 1
GRANT USAGE ON DATABASE DEMOREPO_DB TO ROLE DEMO1_ROLE;

---version: 2
GRANT USAGE ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;

---version: 3
GRANT CREATE TABLE ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;

---version: 4
GRANT CREATE VIEW ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;
