
CREATE ROLE IF NOT EXISTS DEMO1_ROLE;
---rollback:
DROP ROLE IF EXISTS DEMO1_ROLE;

---version: 0
GRANT USAGE ON DATABASE DEMOREPO_DB TO ROLE DEMO1_ROLE;

---version: 1
GRANT USAGE ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;

---version: 2
GRANT CREATE TABLE ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;

---version: 3
GRANT CREATE VIEW ON SCHEMA DEMOREPO_DB.DEMO_SCHEMA TO ROLE DEMO1_ROLE;
